"""create offers table

Revision ID: 5150693ac47e
Revises: 
Create Date: 2025-05-08 21:23:05.892265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5150693ac47e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('last_refresh_time', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('stan', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    # ### end Alembic commands ###
